# Generated by Django 5.2.8 on 2025-12-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('birth_year', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Anders')], max_length=1)),
                ('vdot', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('athletes', models.ManyToManyField(blank=True, related_name='groups', to='core.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_index', models.PositiveSmallIntegerField(choices=[(1, 'Slot 1'), (2, 'Slot 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(blank=True, related_name='training_slots', to='core.athlete')),
                ('groups', models.ManyToManyField(blank=True, related_name='training_slots', to='core.group')),
            ],
            options={
                'ordering': ['-date', 'slot_index'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('WU', 'WU'), ('CORE', 'Core'), ('SPR', 'Sprints'), ('CD', 'CD')], max_length=10)),
                ('zone', models.CharField(choices=[('1', 'Zone 1'), ('2', 'Zone 2'), ('3', 'Zone 3'), ('4', 'Zone 4'), ('5', 'Zone 5'), ('6', 'Zone 6')], default='1', max_length=1)),
                ('reps', models.PositiveIntegerField(default=1)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.trainingslot')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('rpe', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.athlete')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.trainingslot')),
            ],
            options={
                'ordering': ['-slot__date', 'slot__slot_index', 'athlete__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingslot',
            constraint=models.UniqueConstraint(fields=('date', 'slot_index'), name='unique_trainingslot_per_day_and_slot'),
        ),
        migrations.AddConstraint(
            model_name='traininglog',
            constraint=models.UniqueConstraint(fields=('slot', 'athlete'), name='unique_log_per_slot_and_athlete'),
        ),
    ]
