# Generated by Django 5.2.8 on 2025-12-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsegment',
            name='parse_message',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='trainingsegment',
            name='parse_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsegment',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
