# Generated by Django 5.2.8 on 2025-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainingsegment_parse_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsegment',
            name='norm_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
