# Generated by Django 5.2.8 on 2025-12-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainingsegment_norm_distance_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsegment',
            name='type',
            field=models.CharField(choices=[('WU', 'WU'), ('CORE', 'Core'), ('MOB', 'Mob/Tech'), ('SPR', 'Sprint'), ('CD', 'CD')], max_length=10),
        ),
    ]
