# Generated by Django 5.2.8 on 2025-12-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trainingsegment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsegment',
            name='special',
            field=models.CharField(blank=True, choices=[('', '—'), ('STRENGTH', 'Strength'), ('RACE', 'Race'), ('IMPORTANT_RACE', 'Important Race')], default='', max_length=20),
        ),
    ]
