# Generated by Django 5.2.8 on 2025-12-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingsegment_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_memberships', to='core.athlete')),
            ],
            options={
                'ordering': ['plan__name', 'athlete__name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(blank=True, related_name='plans', through='core.PlanMembership', to='core.athlete')),
                ('groups', models.ManyToManyField(blank=True, related_name='plans', to='core.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='planmembership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.trainingplan'),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.trainingplan'),
        ),
        migrations.AddConstraint(
            model_name='planmembership',
            constraint=models.UniqueConstraint(fields=('plan', 'athlete'), name='unique_membership_per_plan_and_athlete'),
        ),
    ]
