# Generated by Django 5.2.8 on 2025-12-26 19:31

from django.db import migrations


def create_default_plan_and_attach_slots(apps, schema_editor):
    TrainingPlan = apps.get_model("core", "TrainingPlan")
    TrainingSlot = apps.get_model("core", "TrainingSlot")

    # Maak (of haal op) het default plan
    default_plan, _ = TrainingPlan.objects.get_or_create(
        name="Default"
    )

    # Koppel alle bestaande slots zonder plan aan Default
    TrainingSlot.objects.filter(plan__isnull=True).update(plan=default_plan)


def detach_slots_from_default_plan(apps, schema_editor):
    TrainingPlan = apps.get_model("core", "TrainingPlan")
    TrainingSlot = apps.get_model("core", "TrainingSlot")

    try:
        default_plan = TrainingPlan.objects.get(name="Default")
    except TrainingPlan.DoesNotExist:
        return

    # Reverse: maak plan weer leeg
    TrainingSlot.objects.filter(plan=default_plan).update(plan=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_planmembership_trainingplan_planmembership_plan_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_plan_and_attach_slots,
            reverse_code=detach_slots_from_default_plan,
        ),
    ]

