# Generated by Django 5.2.8 on 2025-12-26 20:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_default_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingslot',
            name='unique_trainingslot_per_day_and_slot',
        ),
        migrations.AlterField(
            model_name='trainingslot',
            name='plan',
            field=models.ForeignKey(default=core.models.get_default_plan_id, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.trainingplan'),
        ),
        migrations.AddConstraint(
            model_name='trainingslot',
            constraint=models.UniqueConstraint(fields=('plan', 'date', 'slot_index'), name='unique_trainingslot_per_plan_day_and_slot'),
        ),
    ]
