# Generated by Django 5.2.8 on 2026-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_trainingslot_unique_trainingslot_per_plan_day_and_slot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingslot',
            name='unique_base_slot_per_plan_day_slot',
        ),
        migrations.RemoveConstraint(
            model_name='trainingslot',
            name='unique_override_slot_per_plan_athlete_day_slot',
        ),
        migrations.AddConstraint(
            model_name='trainingslot',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', True)), fields=('plan', 'date', 'slot_index'), name='unique_base_slot_per_plan_day_and_slot'),
        ),
        migrations.AddConstraint(
            model_name='trainingslot',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', False)), fields=('plan', 'athlete', 'date', 'slot_index'), name='unique_override_slot_per_plan_athlete_day_and_slot'),
        ),
    ]
