# Generated by Django 5.2.8 on 2026-01-09 21:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_trainingslot_unique_base_slot_per_plan_day_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='zone_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('pb', 'PB'), ('hr', 'HR'), ('lactate', 'Lactate')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='zone_speed_mps',
            field=models.JSONField(blank=True, default=core.models.default_zone_speed_mps),
        ),
    ]
