# Generated by Django 5.2.8 on 2026-01-10 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_athlete_zone_method_athlete_zone_speed_mps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_all_zones', models.BooleanField(default=True)),
                ('highlight_current_week', models.BooleanField(default=True)),
                ('zone_input_unit', models.CharField(default='pace', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
