# Generated by Django 5.2.8 on 2026-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_coachsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsegment',
            name='type',
            field=models.CharField(choices=[('WU', 'WU'), ('CORE', 'Core'), ('CORE2', '2nd Core'), ('ALT', 'Alternative'), ('MOB', 'Mob/Tech'), ('SPR', 'Sprint'), ('CD', 'CD')], max_length=10),
        ),
    ]
