# Generated by Django 5.2.8 on 2026-01-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trainingsegment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='tb_show_cd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachsettings',
            name='tb_show_core2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachsettings',
            name='tb_show_mob',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachsettings',
            name='tb_show_sprint',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachsettings',
            name='tb_show_wu',
            field=models.BooleanField(default=True),
        ),
    ]
