# Generated by Django 5.2.8 on 2026-01-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coachsettings_tb_show_cd_coachsettings_tb_show_core2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='calendar_show_only_core',
            field=models.BooleanField(default=True),
        ),
    ]
