# Generated by Django 5.2.8 on 2026-01-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coachsettings_calendar_show_only_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='weekcolors_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='week_phases_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PlanWeekPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('phase', models.CharField(blank=True, choices=[('', '—'), ('recovery', 'Recovery'), ('aerobe', 'Aerobe'), ('specific', 'Specific'), ('intense', 'Intense'), ('taper', 'Taper')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_phases', to='core.trainingplan')),
            ],
            options={
                'ordering': ['plan__name', 'week_start'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'week_start'), name='unique_week_phase_per_plan_and_week_start')],
            },
        ),
    ]
