# Generated by Django 5.2.8 on 2026-01-11 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coachsettings_weekcolors_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteWeekPhaseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('phase', models.CharField(blank=True, choices=[('', '—'), ('recovery', 'Recovery'), ('aerobe', 'Aerobe'), ('specific', 'Specific'), ('intense', 'Intense'), ('taper', 'Taper')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_phase_overrides', to='core.athlete')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_week_phase_overrides', to='core.trainingplan')),
            ],
            options={
                'ordering': ['plan__name', 'athlete__name', 'week_start'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'athlete', 'week_start'), name='unique_week_phase_override_per_plan_athlete_week')],
            },
        ),
    ]
