# Generated by Django 5.2.8 on 2026-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coachaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='pr_10000_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_1500_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_3000_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_5000_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_800_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
