# Generated by Django 5.2.8 on 2026-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_athlete_pr_10000_s_athlete_pr_1500_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsegment',
            name='t_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('800', 'T800'), ('1500', 'T1500'), ('3000', 'T3000'), ('5000', 'T5000'), ('10000', 'T10000')], default='', max_length=10),
        ),
    ]
