# Generated by Django 5.2.8 on 2026-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_trainingsegment_t_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='pr_10000_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='pr_1500_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='pr_3000_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='pr_5000_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='pr_800_s',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
