# Generated by Django 5.2.8 on 2026-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_athlete_pr_10000_s_alter_athlete_pr_1500_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
