# Generated by Django 5.2.8 on 2026-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_athlete_is_private_trainingplan_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='pr_400_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_thm_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_tm_s',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
