# Generated by Django 5.2.8 on 2026-04-27 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_athletedaycheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='athletedaycheck',
            name='unique_check_per_day_athlete',
        ),
        migrations.AddField(
            model_name='athletedaycheck',
            name='slot_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='athletedaycheck',
            constraint=models.UniqueConstraint(fields=('date', 'athlete', 'slot_index'), name='unique_check_per_day_athlete_slot'),
        ),
    ]
