# Generated by Django 5.2.8 on 2026-04-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_athletedayslotoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletedaycheck',
            name='status',
            field=models.CharField(blank=True, choices=[('', '—'), ('done_as_planned', '✓ Training done as planned'), ('too_hard_fast', '↑ Too much / too fast'), ('adjusted_ok', '✓ Adjusted, not harder or easier'), ('lighter_slower', '↓ Lighter / slower'), ('not_done', '✕ Training not done')], default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='AthleteDaySlotOverride',
        ),
    ]
