# Generated by Django 5.2.8 on 2026-05-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_athletedaycheck_status_delete_athletedayslotoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsegment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
