# Generated by Django 5.2.8 on 2026-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_trainingsegment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='view_weeks_ahead',
            field=models.IntegerField(default=2),
        ),
    ]
