# Generated by Django 5.2.8 on 2026-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_athlete_view_weeks_ahead'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletedaycheck',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='athletedaycheck',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
