# Generated by Django 5.2.8 on 2026-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_race_entry_athlete_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='daily_vitals_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='training_reports_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='week_report_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
