# Generated by Django 5.2.8 on 2026-06-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_athlete_daily_vitals_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteWeekReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('comm_athlete', models.TextField(blank=True, default='')),
                ('comm_trainer', models.TextField(blank=True, default='')),
                ('match_report', models.TextField(blank=True, default='')),
                ('injuries', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_reports', to='core.athlete')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_week_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'athlete__name'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'week_start'), name='unique_week_report_per_athlete_week')],
            },
        ),
    ]
