# Generated by Django 5.2.8 on 2026-06-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_athleteweekreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteDailyVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('morning_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_vitals', to='core.athlete')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_daily_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'athlete__name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'athlete'), name='unique_daily_vitals_per_day_athlete')],
            },
        ),
    ]
