# Generated by Django 5.2.8 on 2026-06-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_athletedailyvital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletedailyvital',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
