# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_raceeventdistance_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="auto_cd_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="athlete",
            name="auto_wu_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="athlete",
            name="auto_wucd_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coachsettings",
            name="auto_cd_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coachsettings",
            name="auto_wu_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coachsettings",
            name="auto_wucd_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
