# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_wucd_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="auto_cd_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="auto_wu_m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="auto_wucd_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
