# Generated by Django 5.2.8 on 2026-07-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_athletedaycheck_watch_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletebaseplanningblock',
            name='planning_kind',
            field=models.CharField(choices=[('base', 'Base planning'), ('ideal', 'Ideal week')], db_index=True, default='base', max_length=20),
        ),
    ]
