# Generated by Django 5.2.8 on 2026-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_polarconnection_v4_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsegment',
            name='type',
            field=models.CharField(choices=[('WU', 'WU'), ('CORE', 'Main'), ('CORE2', 'Main 2'), ('ALT', 'Alternative'), ('MOB', 'Mob/Tech'), ('SPR', 'Sprint'), ('CD', 'CD')], max_length=10),
        ),
    ]
