# Generated by Django 5.2.8 on 2026-08-16 02:13

from django.db import migrations, models


def confirm_existing_race_entries(apps, schema_editor):
    RaceEntry = apps.get_model("core", "RaceEntry")
    RaceEntry.objects.filter(
        models.Q(coach_selected=True)
        | models.Q(athlete_selected=True)
        | models.Q(target_selected=True)
    ).update(coach_selected=True, athlete_selected=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_trainingsegment_type'),
    ]

    operations = [
        migrations.RunPython(confirm_existing_race_entries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trainingsegment',
            name='special',
            field=models.CharField(blank=True, choices=[('', '—'), ('STRENGTH', 'Strength'), ('RACE', 'Race'), ('IMPORTANT_RACE', 'Important Race'), ('RACE_PENDING', 'Race awaiting agreement'), ('RACE_TARGET_PENDING', 'Target race awaiting agreement')], default='', max_length=20),
        ),
    ]
