# Generated by Django 5.2.8 on 2026-08-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_race_agreement_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorosWorkoutPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
