# Generated by Django 5.2.8 on 2026-09-05 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_coachaccess_can_edit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_type', models.CharField(blank=True, choices=[('', '—'), ('recovery', 'Recovery'), ('aerobe', 'Aerobe'), ('specific', 'Specific'), ('intense', 'Intense'), ('taper', 'Taper')], default='', max_length=20)),
                ('whereabouts_type', models.CharField(blank=True, choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('race', 'Race'), ('medical', 'Medical'), ('brinec', 'Brinec')], default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_planner_entries', to='core.athlete')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_planner_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_id', 'athlete__name', 'date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'athlete', 'date'), name='unique_year_planner_entry_per_owner_athlete_date'), models.UniqueConstraint(condition=models.Q(('athlete__isnull', True)), fields=('owner', 'date'), name='unique_year_planner_base_entry_per_owner_date')],
            },
        ),
    ]
