# Generated by Django 5.2.8 on 2026-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_yearplannerwhereabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='pr_1000_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pr_600_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='target_pr_1000_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='target_pr_600_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsegment',
            name='t_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('600', 'T6'), ('800', 'T800'), ('1000', 'T1'), ('1500', 'T1500'), ('3000', 'T3000'), ('5000', 'T5000'), ('10000', 'T10000')], default='', max_length=10),
        ),
    ]
