# Generated by Django 5.2.8 on 2026-09-11 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_matchoverview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAthleteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=160)),
                ('records', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_athlete_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['athlete_name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'athlete_name'), name='unique_match_athlete_record_per_owner')],
            },
        ),
    ]
