# Generated by Django 5.2.8 on 2026-09-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_matchathleterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchathleterecord',
            name='atletiek_nu_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
