# Generated by Django 5.2.8 on 2026-09-18 20:16

from django.db import migrations, models


def move_legacy_race_to_championship(apps, schema_editor):
    YearPlannerEntry = apps.get_model("core", "YearPlannerEntry")
    YearPlannerWhereabout = apps.get_model("core", "YearPlannerWhereabout")
    YearPlannerEntry.objects.filter(whereabouts_type="race").update(whereabouts_type="championship")
    YearPlannerWhereabout.objects.filter(whereabouts_type="race").update(whereabouts_type="championship")


def move_championship_back_to_legacy_race(apps, schema_editor):
    YearPlannerEntry = apps.get_model("core", "YearPlannerEntry")
    YearPlannerWhereabout = apps.get_model("core", "YearPlannerWhereabout")
    YearPlannerEntry.objects.filter(whereabouts_type="championship").update(whereabouts_type="race")
    YearPlannerWhereabout.objects.filter(whereabouts_type="championship").update(whereabouts_type="race")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_matchathleterecord_atletiek_nu_id'),
    ]

    operations = [
        migrations.RunPython(move_legacy_race_to_championship, move_championship_back_to_legacy_race),
        migrations.AlterField(
            model_name='yearplannerentry',
            name='whereabouts_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearplannerwhereabout',
            name='whereabouts_type',
            field=models.CharField(choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], max_length=20),
        ),
    ]
