# Generated by Django 5.2.8 on 2026-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_yearplannerentry_whereabouts_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplannerentry',
            name='whereabouts_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('race_other', 'Race Other'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearplannerwhereabout',
            name='whereabouts_type',
            field=models.CharField(choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('race_other', 'Race Other'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], max_length=20),
        ),
    ]
