# Generated by Django 5.2.8 on 2026-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_yearplannerentry_whereabouts_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='year_planner_training_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='year_planner_whereabouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
