# Generated by Django 5.2.8 on 2026-09-24 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_athlete_year_planner_training_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplannerentry',
            name='whereabouts_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('diamond_l', 'Diamond L'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('race_other', 'Race Other'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearplannerwhereabout',
            name='whereabouts_type',
            field=models.CharField(choices=[('', '—'), ('camp', 'Camp'), ('travel', 'Travel'), ('test', 'Test'), ('championship', 'Championship'), ('diamond_l', 'Diamond L'), ('race_gold', 'Race Gold'), ('race_silver', 'Race Silver'), ('race_bronze', 'Race Bronze'), ('race_other', 'Race Other'), ('expermeetings', 'Expermeetings'), ('medical', 'Medical'), ('brinec', 'Brinec')], max_length=20),
        ),
        migrations.CreateModel(
            name='EvaluationQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.evaluationquestionnaire')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_responses', to='core.athlete')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.evaluationquestionnaire')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'athlete'), name='unique_evaluation_response_per_athlete')],
            },
        ),
    ]
