# Generated by Django 5.2.8 on 2026-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_yearplannerentry_whereabouts_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationquestion',
            name='matrix_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='matrix_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('matrix', 'Matrix')], default='text', max_length=16),
        ),
    ]
