# Generated by Django 5.2.8 on 2026-09-28 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_evaluationquestion_matrix_columns_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='yearplannerentry',
            name='unique_year_planner_base_entry_per_owner_date',
        ),
        migrations.AddField(
            model_name='yearplannerentry',
            name='basis_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_planner_basis_entries', to='core.trainingplan'),
        ),
        migrations.AddField(
            model_name='yearplannerwhereabout',
            name='basis_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_planner_basis_whereabouts', to='core.trainingplan'),
        ),
        migrations.AddConstraint(
            model_name='yearplannerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', True), ('basis_plan__isnull', False)), fields=('owner', 'basis_plan', 'date'), name='unique_year_planner_base_entry_per_plan_date'),
        ),
    ]
