# Generated by Django 5.2.8 on 2026-09-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_yearplannerentry_unique_year_planner_base_entry_per_owner_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='zone_hr_bpm',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
