# Generated by Django 5.2.8 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_redact_polar_token_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachsettings",
            name="detailed_camps_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
