# Generated by Django 5.2.8 on 2026-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_coachsettings_detailed_camps_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplannerwhereabout',
            name='arrival_flight_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='yearplannerwhereabout',
            name='arrival_flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearplannerwhereabout',
            name='departure_flight_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='yearplannerwhereabout',
            name='departure_flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
