# Generated by Django 5.2.8 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_yearplannerwhereabout_arrival_flight_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="extended_edit_rights",
            field=models.BooleanField(default=False),
        ),
    ]
