# Generated by Django 5.2.8 on 2026-10-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_athlete_extended_edit_rights"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="UserWish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("active", "Active"), ("planned", "Used for a plan"), ("cancelled", "Cancelled")], default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="submitted_wishes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PlannedChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("urgency", models.CharField(blank=True, choices=[("", "No medal"), ("gold", "Gold"), ("silver", "Silver"), ("bronze", "Bronze")], default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_wish", models.OneToOneField(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="resulting_plan", to="core.userwish")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="WishLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="wish_likes", to=settings.AUTH_USER_MODEL)),
                ("wish", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="likes", to="core.userwish")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("wish", "user"), name="unique_wish_like_per_user")],
            },
        ),
    ]
