# Generated by Django 5.2.8 on 2026-10-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_new_plans_wishes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("plan", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="likes", to="core.plannedchange")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="plan_likes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("plan", "user"), name="unique_plan_like_per_user")],
            },
        ),
    ]
