# Generated by Django 5.2.8 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_planlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearplannerwhereabout",
            name="accommodation",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="yearplannerwhereabout",
            name="rental_car_info",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
