# Generated by Django 5.2.8 on 2026-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_yearplannerwhereabout_travel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='live_sharing_training_schedules',
            field=models.BooleanField(default=False),
        ),
    ]
