# Generated by Django 5.2.8 on 2026-10-05 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_coachsettings_live_sharing_training_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletebaseplanningblock',
            name='effective_from',
            field=models.DateField(db_index=True, default=datetime.date(1900, 1, 1)),
        ),
    ]
