# Generated by Django 5.2.8 on 2026-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_athletebaseplanningblock_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='can_change_base_planning',
            field=models.BooleanField(default=False),
        ),
    ]
