# Generated by Django 5.2.8 on 2026-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_athlete_shared_year_planner_whereabouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='evaluations_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
