# Generated by Django 5.2.8 on 2026-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_coachsettings_evaluation_sharing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsettings',
            name='focus_points_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
