# Generated by Django 5.2.8 on 2026-10-10 18:28

import django.db.models.deletion
from django.db import migrations, models


def seed_teams_and_coach_settings(apps, schema_editor):
    Team = apps.get_model("core", "Team")
    CoachSettings = apps.get_model("core", "CoachSettings")
    User = apps.get_model("auth", "User")

    for name in ("Atverni", "LLG", "Pace"):
        Team.objects.get_or_create(name=name)

    for user in User.objects.filter(is_staff=True):
        CoachSettings.objects.get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_coachsettings_focus_points_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='core.team'),
        ),
        migrations.AddField(
            model_name='coachsettings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_settings', to='core.team'),
        ),
        migrations.RunPython(seed_teams_and_coach_settings, migrations.RunPython.noop),
    ]
