# Generated by Django 5.2.8 on 2026-10-10 20:00

from django.db import migrations, models


def set_default_team_colors(apps, schema_editor):
    Team = apps.get_model("core", "Team")
    Team.objects.filter(name__iexact="LLG").update(
        color_1="#2B2F6F",
        color_2="#81B747",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_create_coach_settings_for_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color_1',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='color_2',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.RunPython(set_default_team_colors, migrations.RunPython.noop),
    ]
